### ISSUE TITLE
Issue running the app

### ISSUE THREAD

**Issue by verisgit** [VladimirKalachikhin/naiveNMEAdaemon#1]
Hi there, thanks for sharing this. Trying to get it running and finding the following error:

`>php naiveNMEAdaemon.php -b=tcp://localhost:2222 -iNMEA.log -t1000000 --savesentences=resulting.nmea

Created streem socket server. Go to wait loop.

We'll send NMEA sentences correcting the number of visible satellites to 06 and correcting the time of message creation to now and with writing sentences to resulting.nmea.

Wait for first connection on tcp://localhost:2222
Warning: stream_socket_accept(): Accept failed: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond in M:\Source Control\NMEADaemon\naiveNMEAdaemon.php on line 86
Sending NMEA.log with delay 1000000ms per string

Fatal error: Uncaught TypeError: fclose(): Argument #1 ($stream) must be of type resource, bool given in M:\Source Control\NMEADaemon\naiveNMEAdaemon.php:304
Stack trace:
#0 M:\Source Control\NMEADaemon\naiveNMEAdaemon.php(304): fclose(false)
#1 {main}
  thrown in M:\Source Control\NMEADaemon\naiveNMEAdaemon.php on line 304`

**Comment by VladimirKalachikhin** [comment]
Sorry, I didn't promise it would work under Windows. Please do not contact me with errors from Windows.

But, as an exception:
As I understand it, it's just timeout of inbound connection waiting. It's not a bug, it's a feature.
